spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wide
    username: widecore
    password: widecore
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update